name: Deploy AICC Test
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to FreeASPHosting
        uses: webfactory/windows-deploy-action@v1
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
